### ISSUE TITLE
TikTokDiffusion.bat not working

### ISSUE THREAD

**Issue by Mr-small-2-six** [TingTingin/TikTokDiffusion#1]
TikTokDiffusion.bat not working at all,and no have log i can check what problem

have request python  version, or window  version?

**Comment by TingTingin** [comment]
what happens when you click it? what os are you on btw?

**Comment by Mr-small-2-six** [comment]
when i click ,cmd window just close,i am using win11

**Comment by TingTingin** [comment]
edit the file to this 

@echo off
call "venv\Scripts\activate.bat"
python TikTokDiffusion\TikTokDiffusion.py"
pause

then run it

**Comment by TingTingin** [comment]
you have python installed? 
edit: actually nevermind it shouldn't matter

**Comment by Mr-small-2-six** [comment]
Traceback (most recent call last):
  File "G:\ai\stable-diffusion-webui\TikTokDiffusion\TikTokDiffusion.py", line 10, in <module>
    import yt_dlp
ModuleNotFoundError: No module named 'yt_dlp'

just show this

**Comment by TingTingin** [comment]
I updated the file try redownloading

**Comment by Mr-small-2-six** [comment]
File "G:\ai\stable-diffusion-webui\TikTokDiffusion\TikTokDiffusion.py", line 70, in <module>
    check_requirements()
  File "G:\ai\stable-diffusion-webui\TikTokDiffusion\TikTokDiffusion.py", line 48, in check_requirements
    package_search = importlib.util.find_spec(re.sub("[><]=.+", "", search_name))
AttributeError: module 'importlib' has no attribute 'util'

**Comment by TingTingin** [comment]
you have automatic1111 installed?

**Comment by Mr-small-2-six** [comment]
ya using a1111 stable-diffusion-webui,or my file name ai need to chg automatic1111?

**Comment by TingTingin** [comment]
changing the name shouldnt change anything

**Comment by TingTingin** [comment]
edit you tiktokdiffusion.py file replacing the top part with this 

```
import shutil
import time
import glob
import os.path
import subprocess
from importlib import util
import sys
import re

reqs = {'gitpython': ['pip show gitpython', "WARNING"],
        'ipython': ['pip show ipython', "WARNING"],
        'matplotlib': "matplotlib>=3.2.2",
        'numpy': "numpy<=1.23.5",
        'cv2': "opencv-python>=4.1.1'",
        'orjson': "orjson",
        'PIL': "Pillow>=7.1.2",
        'psutil': "psutil",
        'yaml': "PyYAML>=5.3.1",
        'requests': "requests>=2.23.0",
        'scipy': "scipy>=1.4.1",
        'thop': "thop>=0.1.1",
        'SSIM_PIL': "SSIM-PIL",
        'moviepy': "moviepy",
        'sklearn': "scikit-learn",
        'dface': "dface",
        'tqdm': "tqdm>=4.64.0",
        'flet': "flet",
        'static_ffmpeg': "static-ffmpeg",
        'ffmpeg': "ffmpeg-python",
        'tensorboard': "tensorboard",
        'pandas': "pandas",
        'seaborn': "seaborn>=0.11.0",
        'easydict': "easydict>=0.11.0",
        'gdown': "gdown",
        'lap': r"TikTokDiffusion\Assets\whls\lap-0.4.0-cp310-cp310-win_amd64.whl",
        'cython_bbox': r"TikTokDiffusion\Assets\whls\cython_bbox-0.1.3-cp310-cp310-win_amd64.whl",
        'filterpy': "filterpy",
        'pyopencl': 'pyopencl',
        'yt_dlp': "yt-dlp"}


def check_requirements():

    print("Checking TikTokDiffusion...")
    python = sys.executable

    for search_name, req_command in reqs.items():
        package_search = util.find_spec(re.sub("[><]=.+", "", search_name))
        print(f"Checking TikTokDiffusion Requirement: {search_name}")

        present = package_search is not None
        if not present:
            if type(req_command) == list:
                try:
                    pipoutput = subprocess.run(fr'{req_command[0]}', capture_output=True, text=True)
                except Exception as e:
                    print(e)

                if not pipoutput.stdout.find("WARNING") == -1:
                    print(f"Installing TikTokDiffusion Requirement: {search_name}")
                    subprocess.run(fr'"{python}" -m pip install {req_command}')
            else:
                print(f"Installing TikTokDiffusion Requirement: {req_command}")
                try:
                    subprocess.run(fr'"{python}" -m pip install {req_command}')
                except Exception as e:
                    print(e)
```

**Comment by TingTingin** [comment]
you should replace everthing up to this line the line that has check_requirements()

**Comment by Mr-small-2-six** [comment]
Checking TikTokDiffusion...
Checking TikTokDiffusion Requirement: gitpython
Checking TikTokDiffusion Requirement: ipython
Checking TikTokDiffusion Requirement: matplotlib
Checking TikTokDiffusion Requirement: numpy
Checking TikTokDiffusion Requirement: cv2
Checking TikTokDiffusion Requirement: orjson
Checking TikTokDiffusion Requirement: PIL
Checking TikTokDiffusion Requirement: psutil
Checking TikTokDiffusion Requirement: yaml
Checking TikTokDiffusion Requirement: requests
Checking TikTokDiffusion Requirement: scipy
Checking TikTokDiffusion Requirement: thop
Checking TikTokDiffusion Requirement: SSIM_PIL
Checking TikTokDiffusion Requirement: moviepy
Checking TikTokDiffusion Requirement: sklearn
Checking TikTokDiffusion Requirement: dface
Checking TikTokDiffusion Requirement: tqdm
Checking TikTokDiffusion Requirement: flet
Checking TikTokDiffusion Requirement: static_ffmpeg
Checking TikTokDiffusion Requirement: ffmpeg
Checking TikTokDiffusion Requirement: tensorboard
Checking TikTokDiffusion Requirement: pandas
Checking TikTokDiffusion Requirement: seaborn
Checking TikTokDiffusion Requirement: easydict
Checking TikTokDiffusion Requirement: gdown
Checking TikTokDiffusion Requirement: lap
Checking TikTokDiffusion Requirement: cython_bbox
Checking TikTokDiffusion Requirement: filterpy
Checking TikTokDiffusion Requirement: pyopencl
Checking TikTokDiffusion Requirement: yt_dlp
Traceback (most recent call last):
  File "G:\automatic1111\stable-diffusion-webui\TikTokDiffusion\TikTokDiffusion.py", line 75, in <module>
    import track
  File "G:\automatic1111\stable-diffusion-webui\TikTokDiffusion\track.py", line 60, in <module>
    from trackers.multi_tracker_zoo import create_tracker
  File "G:\automatic1111\stable-diffusion-webui\TikTokDiffusion\trackers\multi_tracker_zoo.py", line 4, in <module>
    from trackers.bytetrack.byte_tracker import BYTETracker
  File "G:\automatic1111\stable-diffusion-webui\TikTokDiffusion\trackers\bytetrack\byte_tracker.py", line 13, in <module>
    from trackers.bytetrack import matching
  File "G:\automatic1111\stable-diffusion-webui\TikTokDiffusion\trackers\bytetrack\matching.py", line 7, in <module>
    from cython_bbox import bbox_overlaps as bbox_ious
  File "src\cython_bbox.pyx", line 12, in init cython_bbox
  File "C:\Users\justk\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Comment by TingTingin** [comment]
the problem is having the wrong version of numpy to fix

- go to the folder you have automatic1111 install (the stable diffusion folder) 
- type cmd in the address bar (where the file path is) then enter
- this will open cmd in the current folder 
- then type venv\scripts\activate (this will activate the virtual environment where SD is Installed)
- then type pip uninstall numpy
when you rerun tiktok diffusion it will reinstall the correct numpy version

if you want you could install the correct numpy version yourself by typing

- pip install "numpy<=1.23.5" (after pip uninstall)

**Comment by Mr-small-2-six** [comment]
now can  launch,Thanks alot
i try use 1st
so model need to go webui chg 1st?
if i wan to pick specific one

**Comment by TingTingin** [comment]
you change in webui most webui settings work

**Comment by TingTingin** [comment]
make sure to try short video to start also remember to increase resoulution as 512x512  is generally too low

**Comment by I-ShadowStar** [comment]
I got the TorchVision error, and fixed it with your instructions, but then I got the Numby error. Following your instructions did not fix this, please advise.

> The system cannot find the path specified.
> Checking TikTokDiffusion...
> Checking TikTokDiffusion Requirement: gitpython
> Checking TikTokDiffusion Requirement: ipython
> Checking TikTokDiffusion Requirement: matplotlib
> Checking TikTokDiffusion Requirement: numpy
> Checking TikTokDiffusion Requirement: cv2
> Checking TikTokDiffusion Requirement: orjson
> Checking TikTokDiffusion Requirement: PIL
> Checking TikTokDiffusion Requirement: psutil
> Checking TikTokDiffusion Requirement: yaml
> Checking TikTokDiffusion Requirement: requests
> Checking TikTokDiffusion Requirement: scipy
> Checking TikTokDiffusion Requirement: thop
> Checking TikTokDiffusion Requirement: SSIM_PIL
> Checking TikTokDiffusion Requirement: moviepy
> Checking TikTokDiffusion Requirement: sklearn
> Checking TikTokDiffusion Requirement: dface
> Checking TikTokDiffusion Requirement: tqdm
> Checking TikTokDiffusion Requirement: flet
> Checking TikTokDiffusion Requirement: static_ffmpeg
> Checking TikTokDiffusion Requirement: ffmpeg
> Checking TikTokDiffusion Requirement: tensorboard
> Checking TikTokDiffusion Requirement: pandas
> Checking TikTokDiffusion Requirement: seaborn
> Checking TikTokDiffusion Requirement: easydict
> Checking TikTokDiffusion Requirement: gdown
> Checking TikTokDiffusion Requirement: lap
> Checking TikTokDiffusion Requirement: cython_bbox
> Checking TikTokDiffusion Requirement: filterpy
> Checking TikTokDiffusion Requirement: pyopencl
> Checking TikTokDiffusion Requirement: yt_dlp
> Traceback (most recent call last):
>   File "C:\PANDORA\stable-diffusion-webui\TikTokDiffusion-main\TikTokDiffusion\TikTokDiffusion.py", line 75, in <module>    import track
>   File "C:\PANDORA\stable-diffusion-webui\TikTokDiffusion-main\TikTokDiffusion\track.py", line 60, in <module>
>     from trackers.multi_tracker_zoo import create_tracker
>   File "C:\PANDORA\stable-diffusion-webui\TikTokDiffusion-main\TikTokDiffusion\trackers\multi_tracker_zoo.py", line 4, in <module>
>     from trackers.bytetrack.byte_tracker import BYTETracker
>   File "C:\PANDORA\stable-diffusion-webui\TikTokDiffusion-main\TikTokDiffusion\trackers\bytetrack\byte_tracker.py", line 13, in <module>
>     from trackers.bytetrack import matching
>   File "C:\PANDORA\stable-diffusion-webui\TikTokDiffusion-main\TikTokDiffusion\trackers\bytetrack\matching.py", line 7, in <module>
>     from cython_bbox import bbox_overlaps as bbox_ious
>   File "src\cython_bbox.pyx", line 12, in init cython_bbox
>   File "C:\Users\cygnu\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\__init__.py", line 284, in __getattr__
>     raise AttributeError("module {!r} has no attribute "
> AttributeError: module 'numpy' has no attribute 'float'
> Press any key to continue . . .

**Comment by I-ShadowStar** [comment]
I ran the following command per your instructions on yet another issue about your batch file not working for average users. Please understand, the string of errors is making you look bad. Telling people to manually update their clients makes you look bad. Please re-examine your code for bugs. I am still getting the same errors..

> pip3 install --pre torch torchvision torchaudio --index-url 

> Microsoft Windows [Version 10.0.19044.2604]
> (c) Microsoft Corporation. All rights reserved.
> 
> C:\PANDORA\stable-diffusion-webui\TikTokDiffusion-main>cd..
> 
> C:\PANDORA\stable-diffusion-webui>pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu118
> Looking in indexes: https://download.pytorch.org/whl/nightly/cu118
> Requirement already satisfied: torch in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (1.13.1)
> Requirement already satisfied: torchvision in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (0.14.1)
> Collecting torchaudio
>   Downloading https://download.pytorch.org/whl/nightly/cu118/torchaudio-2.0.0.dev20230221%2Bcu118-cp310-cp310-win_amd64.whl (2.5 MB)
>      ---------------------------------------- 2.5/2.5 MB 26.5 MB/s eta 0:00:00
> Requirement already satisfied: typing-extensions in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from torch) (4.4.0)
> Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from torchvision) (9.4.0)
> Requirement already satisfied: numpy in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from torchvision) (1.24.1)
> Requirement already satisfied: requests in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from torchvision) (2.28.2)
>   Downloading https://download.pytorch.org/whl/nightly/cu118/torchaudio-2.0.0.dev20230220%2Bcu118-cp310-cp310-win_amd64.whl (2.5 MB)
>      ---------------------------------------- 2.5/2.5 MB 52.9 MB/s eta 0:00:00
>   Downloading https://download.pytorch.org/whl/nightly/cu118/torchaudio-2.0.0.dev20230219%2Bcu118-cp310-cp310-win_amd64.whl (2.5 MB)
>      ---------------------------------------- 2.5/2.5 MB 80.3 MB/s eta 0:00:00
>   Downloading https://download.pytorch.org/whl/nightly/cu118/torchaudio-2.0.0.dev20230218%2Bcu118-cp310-cp310-win_amd64.whl (2.5 MB)
>      ---------------------------------------- 2.5/2.5 MB 5.9 MB/s eta 0:00:00
>   Downloading https://download.pytorch.org/whl/nightly/cu118/torchaudio-2.0.0.dev20230217%2Bcu118-cp310-cp310-win_amd64.whl (2.5 MB)
>      ---------------------------------------- 2.5/2.5 MB 40.1 MB/s eta 0:00:00
>   Downloading https://download.pytorch.org/whl/nightly/cu118/torchaudio-2.0.0.dev20230216%2Bcu118-cp310-cp310-win_amd64.whl (2.5 MB)
>      ---------------------------------------- 2.5/2.5 MB 77.6 MB/s eta 0:00:00
>   Downloading https://download.pytorch.org/whl/nightly/cu118/torchaudio-2.0.0.dev20230215%2Bcu118-cp310-cp310-win_amd64.whl (2.5 MB)
>      ---------------------------------------- 2.5/2.5 MB 5.9 MB/s eta 0:00:00
>   Downloading https://download.pytorch.org/whl/nightly/cu118/torchaudio-2.0.0.dev20230214%2Bcu118-cp310-cp310-win_amd64.whl (2.5 MB)
>      ---------------------------------------- 2.5/2.5 MB 5.5 MB/s eta 0:00:00
>   Downloading https://download.pytorch.org/whl/nightly/cu118/torchaudio-2.0.0.dev20230213%2Bcu118-cp310-cp310-win_amd64.whl (2.5 MB)
>      ---------------------------------------- 2.5/2.5 MB 6.9 MB/s eta 0:00:00
>   Downloading https://download.pytorch.org/whl/nightly/cu118/torchaudio-2.0.0.dev20230212%2Bcu118-cp310-cp310-win_amd64.whl (2.5 MB)
>      ---------------------------------------- 2.5/2.5 MB 53.6 MB/s eta 0:00:00
>   Downloading https://download.pytorch.org/whl/nightly/cu118/torchaudio-2.0.0.dev20230211%2Bcu118-cp310-cp310-win_amd64.whl (2.5 MB)
>      ---------------------------------------- 2.5/2.5 MB 77.1 MB/s eta 0:00:00
>   Downloading https://download.pytorch.org/whl/nightly/cu118/torchaudio-2.0.0.dev20230210%2Bcu118-cp310-cp310-win_amd64.whl (2.5 MB)
>      ---------------------------------------- 2.5/2.5 MB 52.5 MB/s eta 0:00:00
>   Downloading https://download.pytorch.org/whl/nightly/cu118/torchaudio-2.0.0.dev20230209%2Bcu118-cp310-cp310-win_amd64.whl (2.5 MB)
>      ---------------------------------------- 2.5/2.5 MB 39.2 MB/s eta 0:00:00
>   Downloading https://download.pytorch.org/whl/nightly/cu118/torchaudio-2.0.0.dev20230208%2Bcu118-cp310-cp310-win_amd64.whl (2.5 MB)
>      ---------------------------------------- 2.5/2.5 MB 79.6 MB/s eta 0:00:00
>   Downloading https://download.pytorch.org/whl/nightly/cu118/torchaudio-2.0.0.dev20230207%2Bcu118-cp310-cp310-win_amd64.whl (2.5 MB)
>      ---------------------------------------- 2.5/2.5 MB 79.6 MB/s eta 0:00:00
>   Downloading https://download.pytorch.org/whl/nightly/cu118/torchaudio-2.0.0.dev20230206%2Bcu118-cp310-cp310-win_amd64.whl (2.5 MB)
>      ---------------------------------------- 2.5/2.5 MB 79.5 MB/s eta 0:00:00
>   Downloading https://download.pytorch.org/whl/nightly/cu118/torchaudio-2.0.0.dev20230205%2Bcu118-cp310-cp310-win_amd64.whl (2.5 MB)
>      ---------------------------------------- 2.5/2.5 MB 52.5 MB/s eta 0:00:00
>   Downloading https://download.pytorch.org/whl/nightly/cu118/torchaudio-2.0.0.dev20230204%2Bcu118-cp310-cp310-win_amd64.whl (2.5 MB)
>      ---------------------------------------- 2.5/2.5 MB 6.1 MB/s eta 0:00:00
>   Downloading https://download.pytorch.org/whl/nightly/cu118/torchaudio-2.0.0.dev20230203%2Bcu118-cp310-cp310-win_amd64.whl (2.4 MB)
>      ---------------------------------------- 2.4/2.4 MB 51.6 MB/s eta 0:00:00
>   Downloading https://download.pytorch.org/whl/nightly/cu118/torchaudio-2.0.0.dev20230202%2Bcu118-cp310-cp310-win_amd64.whl (2.4 MB)
>      ---------------------------------------- 2.4/2.4 MB 78.2 MB/s eta 0:00:00
>   Downloading https://download.pytorch.org/whl/nightly/cu118/torchaudio-2.0.0.dev20230201%2Bcu118-cp310-cp310-win_amd64.whl (2.4 MB)
>      ---------------------------------------- 2.4/2.4 MB 6.2 MB/s eta 0:00:00
>   Downloading https://download.pytorch.org/whl/nightly/cu118/torchaudio-2.0.0.dev20230131%2Bcu118-cp310-cp310-win_amd64.whl (2.4 MB)
>      ---------------------------------------- 2.4/2.4 MB 38.8 MB/s eta 0:00:00
>   Downloading https://download.pytorch.org/whl/nightly/cu118/torchaudio-2.0.0.dev20230130%2Bcu118-cp310-cp310-win_amd64.whl (2.4 MB)
>      ---------------------------------------- 2.4/2.4 MB 77.6 MB/s eta 0:00:00
>   Downloading https://download.pytorch.org/whl/nightly/cu118/torchaudio-2.0.0.dev20230129%2Bcu118-cp310-cp310-win_amd64.whl (2.4 MB)
>      ---------------------------------------- 2.4/2.4 MB 75.1 MB/s eta 0:00:00
>   Downloading https://download.pytorch.org/whl/nightly/cu118/torchaudio-2.0.0.dev20230128%2Bcu118-cp310-cp310-win_amd64.whl (2.4 MB)
>      ---------------------------------------- 2.4/2.4 MB 38.2 MB/s eta 0:00:00
>   Downloading https://download.pytorch.org/whl/nightly/cu118/torchaudio-2.0.0.dev20230127%2Bcu118-cp310-cp310-win_amd64.whl (2.4 MB)
>      ---------------------------------------- 2.4/2.4 MB 51.1 MB/s eta 0:00:00
>   Downloading https://download.pytorch.org/whl/nightly/cu118/torchaudio-2.0.0.dev20230126%2Bcu118-cp310-cp310-win_amd64.whl (2.4 MB)
>      ---------------------------------------- 2.4/2.4 MB 39.0 MB/s eta 0:00:00
>   Downloading https://download.pytorch.org/whl/nightly/cu118/torchaudio-2.0.0.dev20230125%2Bcu118-cp310-cp310-win_amd64.whl (2.4 MB)
>      ---------------------------------------- 2.4/2.4 MB 31.0 MB/s eta 0:00:00
>   Downloading https://download.pytorch.org/whl/nightly/cu118/torchaudio-2.0.0.dev20230124%2Bcu118-cp310-cp310-win_amd64.whl (2.4 MB)
>      ---------------------------------------- 2.4/2.4 MB 51.4 MB/s eta 0:00:00
>   Downloading https://download.pytorch.org/whl/nightly/cu118/torchaudio-2.0.0.dev20230123%2Bcu118-cp310-cp310-win_amd64.whl (2.4 MB)
>      ---------------------------------------- 2.4/2.4 MB 75.6 MB/s eta 0:00:00
>   Downloading https://download.pytorch.org/whl/nightly/cu118/torchaudio-2.0.0.dev20230122%2Bcu118-cp310-cp310-win_amd64.whl (2.4 MB)
>      ---------------------------------------- 2.4/2.4 MB 30.9 MB/s eta 0:00:00
>   Downloading https://download.pytorch.org/whl/nightly/cu118/torchaudio-2.0.0.dev20230121%2Bcu118-cp310-cp310-win_amd64.whl (2.4 MB)
>      ---------------------------------------- 2.4/2.4 MB 51.2 MB/s eta 0:00:00
>   Downloading https://download.pytorch.org/whl/nightly/cu118/torchaudio-2.0.0.dev20230120%2Bcu118-cp310-cp310-win_amd64.whl (2.4 MB)
>      ---------------------------------------- 2.4/2.4 MB 38.2 MB/s eta 0:00:00
>   Downloading https://download.pytorch.org/whl/nightly/cu118/torchaudio-2.0.0.dev20230119%2Bcu118-cp310-cp310-win_amd64.whl (2.4 MB)
>      ---------------------------------------- 2.4/2.4 MB 5.7 MB/s eta 0:00:00
>   Downloading https://download.pytorch.org/whl/nightly/cu118/torchaudio-2.0.0.dev20230118%2Bcu118-cp310-cp310-win_amd64.whl (2.4 MB)
>      ---------------------------------------- 2.4/2.4 MB 77.7 MB/s eta 0:00:00
>   Downloading https://download.pytorch.org/whl/nightly/cu118/torchaudio-2.0.0.dev20230117%2Bcu118-cp310-cp310-win_amd64.whl (2.4 MB)
>      ---------------------------------------- 2.4/2.4 MB 5.9 MB/s eta 0:00:00
>   Downloading https://download.pytorch.org/whl/nightly/cu118/torchaudio-2.0.0.dev20230116%2Bcu118-cp310-cp310-win_amd64.whl (2.4 MB)
>      ---------------------------------------- 2.4/2.4 MB 77.6 MB/s eta 0:00:00
>   Downloading https://download.pytorch.org/whl/nightly/cu118/torchaudio-2.0.0.dev20230115%2Bcu118-cp310-cp310-win_amd64.whl (2.4 MB)
>      ---------------------------------------- 2.4/2.4 MB 51.2 MB/s eta 0:00:00
>   Downloading https://download.pytorch.org/whl/nightly/cu118/torchaudio-2.0.0.dev20230114%2Bcu118-cp310-cp310-win_amd64.whl (2.4 MB)
>      ---------------------------------------- 2.4/2.4 MB 51.2 MB/s eta 0:00:00
>   Downloading https://download.pytorch.org/whl/nightly/cu118/torchaudio-2.0.0.dev20230113%2Bcu118-cp310-cp310-win_amd64.whl (2.4 MB)
>      ---------------------------------------- 2.4/2.4 MB 51.2 MB/s eta 0:00:00
>   Downloading https://download.pytorch.org/whl/nightly/cu118/torchaudio-2.0.0.dev20230112%2Bcu118-cp310-cp310-win_amd64.whl (2.4 MB)
>      ---------------------------------------- 2.4/2.4 MB 38.8 MB/s eta 0:00:00
> INFO: pip is looking at multiple versions of torchvision to determine which version is compatible with other requirements. This could take a while.
> Collecting torchvision
>   Downloading https://download.pytorch.org/whl/nightly/cu118/torchvision-0.15.0.dev20230226%2Bcu118-cp310-cp310-win_amd64.whl (5.1 MB)
>      ---------------------------------------- 5.1/5.1 MB 81.6 MB/s eta 0:00:00
> Collecting torch
>   Downloading https://download.pytorch.org/whl/nightly/cu118/torch-2.0.0.dev20230226%2Bcu118-cp310-cp310-win_amd64.whl (2618.1 MB)
>      ---------------------------------------- 2.6/2.6 GB 1.3 MB/s eta 0:00:00
> Requirement already satisfied: networkx in c:\users\cygnu\appdata\local\programs\python\python310\lib\site-packages (from torch) (3.0)
> Collecting sympy
>   Downloading https://download.pytorch.org/whl/nightly/sympy-1.11.1-py3-none-any.whl (6.5 MB)
>      ---------------------------------------- 6.5/6.5 MB 69.5 MB/s eta 0:00:00
> Requirement already satisfied: filelock in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from torch) (3.9.0)
> INFO: pip is looking at multiple versions of torch to determine which version is compatible with other requirements. This could take a while.
> INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
> Collecting torchvision
>   Downloading https://download.pytorch.org/whl/nightly/cu118/torchvision-0.15.0.dev20230224%2Bcu118-cp310-cp310-win_amd64.whl (5.1 MB)
>      ---------------------------------------- 5.1/5.1 MB 80.3 MB/s eta 0:00:00
> Collecting torch
>   Downloading https://download.pytorch.org/whl/nightly/cu118/torch-2.0.0.dev20230224%2Bcu118-cp310-cp310-win_amd64.whl (2618.1 MB)
>      ---------------------------------------- 2.6/2.6 GB 1.3 MB/s eta 0:00:00
> Collecting torchvision
>   Downloading https://download.pytorch.org/whl/nightly/cu118/torchvision-0.15.0.dev20230220%2Bcu118-cp310-cp310-win_amd64.whl (5.1 MB)
>      ---------------------------------------- 5.1/5.1 MB 10.8 MB/s eta 0:00:00
> Collecting torch
>   Downloading https://download.pytorch.org/whl/nightly/cu118/torch-2.0.0.dev20230220%2Bcu118-cp310-cp310-win_amd64.whl (2618.1 MB)
>      ---------------------------------------- 2.6/2.6 GB ? eta 0:00:00
> Requirement already satisfied: certifi>=2017.4.17 in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from requests->torchvision) (2022.12.7)
> Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from requests->torchvision) (1.26.14)
> Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from requests->torchvision) (3.0.1)
> Requirement already satisfied: idna<4,>=2.5 in c:\users\XXX\appdata\local\programs\python\python310\lib\site-packages (from requests->torchvision) (3.4)
> Collecting mpmath>=0.19
>   Downloading https://download.pytorch.org/whl/nightly/mpmath-1.2.1-py3-none-any.whl (532 kB)
>      ---------------------------------------- 532.6/532.6 kB 34.8 MB/s eta 0:00:00
> Installing collected packages: mpmath, sympy, torch, torchvision, torchaudio
>   Attempting uninstall: torch
>     Found existing installation: torch 1.13.1
>     Uninstalling torch-1.13.1:
>       Successfully uninstalled torch-1.13.1
>   Attempting uninstall: torchvision
>     Found existing installation: torchvision 0.14.1
>     Uninstalling torchvision-0.14.1:
>       Successfully uninstalled torchvision-0.14.1
> Successfully installed mpmath-1.2.1 sympy-1.11.1 torch-2.0.0.dev20230220+cu118 torchaudio-2.0.0.dev20230221+cu118 torchvision-0.15.0.dev20230220+cu118
> 
> [notice] A new release of pip available: 22.3.1 -> 23.0.1
> [notice] To update, run: python.exe -m pip install --upgrade pip

**Comment by TingTingin** [comment]
The program is in alpha it wont be updated for a while and when it does it will be a big update if that's what your need for it to work then you either wait for that update or you can try to fix the problems manually 

Also what error are you having the log you posted doesn't show an error its also from stable diffusion UI not tiktok diffusion

**Comment by TingTingin** [comment]
> The program is in alpha it wont be updated for a while and when it does it will be a big update

Actually I might make a small bugfix update soon (Within the next few days) though I still don't know what problem your having

**Comment by ecureuilfourbe** [comment]
I don't know if this help but, try to put the **_CONTENT_**  of the TikTokDiffusion-main folder in your stable-diffusion-webui folder, not the TikTokDiffusion-main folder itself, I made the same mistake :) 

![image](https://user-images.githubusercontent.com/36704066/221674175-3f489f19-8cdb-49d3-a14f-aa5142368844.png)
