### ISSUE TITLE
Was working perfectly until ControlNet 1.1, but broken regardless of reverting controlnet or running in Automatic1111 or Vlad

### ISSUE THREAD

**Issue by drsgtnash** [TingTingin/TikTokDiffusion#21]
ERROR

generating prompt: 'ariana grande' for person 1
generating prompt: 'ariana grande' for person 1
Exception in thread Thread-62 (this_func):
Traceback (most recent call last):
  File "C:\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "X:\stable-diffusion-webui-master\TikTokDiffusion\TikTokDiffusion.py", line 1109, in this_func
    track.run(
  File "X:\stable-diffusion-webui-master\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "X:\stable-diffusion-webui-master\TikTokDiffusion\track.py", line 951, in run
    image = api.img2img(images=[gen_image],
  File "X:\stable-diffusion-webui-master\TikTokDiffusion\webuiapi.py", line 258, in img2img
    return self._to_api_result(response)
  File "X:\stable-diffusion-webui-master\TikTokDiffusion\webuiapi.py", line 51, in _to_api_result
    raise RuntimeError(response.status_code, response.text)
RuntimeError: (500, '{"error":"RuntimeError","detail":"","body":"","errors":"Given groups=1, weight of size [64, 3, 3, 3], expected input[1, 4, 192, 192] to have 3 channels, but got 4 channels instead"}')

-------------------------------------------------------------------------------------------------

Originally thought it was a LyCORIS problem, but even basic prompts or changing the checkpoint is causing problems.

Any help is appreciated

**Comment by drsgtnash** [comment]
Now this is what shows up in the other window


╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ X:\stable-diffusion-webui-master\venv\lib\site-packages\anyio\streams\memory.py:94 in receive                        │
│                                                                                                                      │
│ X:\stable-diffusion-webui-master\venv\lib\site-packages\anyio\streams\memory.py:89 in receive_nowait                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
WouldBlock

During handling of the above exception, another exception occurred:

╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ X:\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\base.py:78 in call_next                 │
│                                                                                                                      │
│ X:\stable-diffusion-webui-master\venv\lib\site-packages\anyio\streams\memory.py:114 in receive                       │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
EndOfStream

During handling of the above exception, another exception occurred:

╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ X:\stable-diffusion-webui-master\modules\api\api.py:145 in exception_handling                                        │
│                                                                                                                      │
│   144 │   │   try:                                                                                                   │
│ ❱ 145 │   │   │   return await call_next(request)                                                                    │
│   146 │   │   except Exception as e:                                                                                 │
│                                                                                                                      │
│ ╭───────────────────────────────────────────────────── locals ─────────────────────────────────────────────────────╮ │
│ │        call_next = <function BaseHTTPMiddleware.__call__.<locals>.call_next at 0x000002586DFE0280>               │ │
│ │                e = RuntimeError('Given groups=1, weight of size [64, 3, 3, 3], expected input[1, 4, 192, 192] to │ │
│ │                    have 3 channels, but got 4 channels instead')                                                 │ │
│ │ handle_exception = <function api_middleware.<locals>.handle_exception at 0x000002571E6F83A0>                     │ │
│ │          request = <starlette.requests.Request object at 0x000002586DBE9FC0>                                     │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                                      │
│ X:\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\base.py:84 in call_next                 │
│                                                                                                                      │
│                                               ... 38 frames hidden ...                                               │
│                                                                                                                      │
│ X:\stable-diffusion-webui-master\venv\lib\site-packages\torch\nn\modules\conv.py:463 in forward                      │
│                                                                                                                      │
│    462 │   def forward(self, input: Tensor) -> Tensor:                                                               │
│ ❱  463 │   │   return self._conv_forward(input, self.weight, self.bias)                                              │
│    464                                                                                                               │
│                                                                                                                      │
│ ╭─────────────────────────────────── locals ───────────────────────────────────╮                                     │
│ │ input = tensor([[[[1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],    │                                     │
│ │         │   │     [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],    │                                     │
│ │         │   │     [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],    │                                     │
│ │         │   │     ...,                                                       │                                     │
│ │         │   │     [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],    │                                     │
│ │         │   │     [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],    │                                     │
│ │         │   │     [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000]],   │                                     │
│ │         │   │                                                                │                                     │
│ │         │   │    [[0.0471, 0.0549, 0.0431,  ..., 0.0549, 0.0549, 0.0549],    │                                     │
│ │         │   │     [0.0392, 0.0392, 0.0431,  ..., 0.0706, 0.0549, 0.0627],    │                                     │
│ │         │   │     [0.0431, 0.0510, 0.0510,  ..., 0.0627, 0.0627, 0.0627],    │                                     │
│ │         │   │     ...,                                                       │                                     │
│ │         │   │     [0.0824, 0.0784, 0.0706,  ..., 0.0235, 0.0235, 0.0275],    │                                     │
│ │         │   │     [0.0706, 0.0745, 0.0745,  ..., 0.0275, 0.0275, 0.0235],    │                                     │
│ │         │   │     [0.0667, 0.0667, 0.0667,  ..., 0.0314, 0.0314, 0.0314]],   │                                     │
│ │         │   │                                                                │                                     │
│ │         │   │    [[0.0902, 0.0902, 0.0863,  ..., 0.1020, 0.0980, 0.0980],    │                                     │
│ │         │   │     [0.0980, 0.0980, 0.1020,  ..., 0.1137, 0.1098, 0.1137],    │                                     │
│ │         │   │     [0.0863, 0.1020, 0.1020,  ..., 0.1059, 0.1059, 0.1059],    │                                     │
│ │         │   │     ...,                                                       │                                     │
│ │         │   │     [0.1137, 0.1098, 0.1098,  ..., 0.0745, 0.0706, 0.0784],    │                                     │
│ │         │   │     [0.1098, 0.1216, 0.1137,  ..., 0.0784, 0.0745, 0.0745],    │                                     │
│ │         │   │     [0.1098, 0.1098, 0.1098,  ..., 0.0784, 0.0784, 0.0824]],   │                                     │
│ │         │   │                                                                │                                     │
│ │         │   │    [[0.0706, 0.0667, 0.0667,  ..., 0.0941, 0.0980, 0.1020],    │                                     │
│ │         │   │     [0.0471, 0.0471, 0.0510,  ..., 0.1059, 0.0941, 0.1098],    │                                     │
│ │         │   │     [0.0667, 0.0549, 0.0549,  ..., 0.1020, 0.1020, 0.1020],    │                                     │
│ │         │   │     ...,                                                       │                                     │
│ │         │   │     [0.0706, 0.0706, 0.0706,  ..., 0.0510, 0.0706, 0.0549],    │                                     │
│ │         │   │     [0.0706, 0.0706, 0.0745,  ..., 0.0549, 0.0706, 0.0510],    │                                     │
│ │         │   │     [0.0588, 0.0588, 0.0588,  ..., 0.0745, 0.0745, 0.0588]]]], │                                     │
│ │         │      device='cuda:0')                                              │                                     │
│ │  self = Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))     │                                     │
│ ╰──────────────────────────────────────────────────────────────────────────────╯                                     │
│                                                                                                                      │
│ X:\stable-diffusion-webui-master\venv\lib\site-packages\torch\nn\modules\conv.py:459 in _conv_forward                │
│                                                                                                                      │
│    458 │   │   │   │   │   │   │   _pair(0), self.dilation, self.groups)                                             │
│ ❱  459 │   │   return F.conv2d(input, weight, bias, self.stride,                                                     │
│    460 │   │   │   │   │   │   self.padding, self.dilation, self.groups)                                             │
│                                                                                                                      │
│ ╭──────────────────────────────────────── locals ────────────────────────────────────────╮                           │
│ │   bias = Parameter containing:                                                         │                           │
│ │          tensor([ 2.4883e-02, -6.4579e-02,  1.3129e-02,  1.0378e-01,  1.6449e-02,      │                           │
│ │          │   │    9.4825e-02,  3.2137e-02,  2.4335e-03,  1.7125e-01, -4.1086e-03,      │                           │
│ │          │   │    1.4483e-02,  3.3739e-03, -6.3326e-02,  6.8827e-02, -6.7050e-02,      │                           │
│ │          │   │   -1.4726e-02, -1.9091e-02, -4.2491e-03,  9.2902e-05, -1.0080e-02,      │                           │
│ │          │   │   -3.4603e-02, -1.8759e-02, -3.3707e-02,  4.4093e-03,  4.2929e-02,      │                           │
│ │          │   │   -1.3341e-02, -6.5829e-03, -6.1598e-03, -1.4455e-02,  4.7949e-03,      │                           │
│ │          │   │   -1.1129e-02,  1.0500e-02, -5.0182e-02, -1.1967e-02, -1.4324e-02,      │                           │
│ │          │   │   -1.3070e-02,  4.4609e-02, -9.7306e-03,  2.0383e-03,  5.0906e-02,      │                           │
│ │          │   │   -2.4988e-03,  6.3599e-02, -3.8255e-02, -1.7741e-03, -2.1395e-02,      │                           │
│ │          │   │    1.2647e-02, -6.9446e-03,  3.2541e-02, -9.5755e-03, -1.4555e-02,      │                           │
│ │          │   │   -6.2574e-04,  4.7982e-02,  9.5271e-02,  5.7437e-03, -1.5118e-03,      │                           │
│ │          │   │   -1.4437e-02,  1.8010e-02, -9.2134e-02, -6.1387e-03, -8.9283e-02,      │                           │
│ │          │   │   -2.0173e-01,  3.1718e-02,  6.9428e-03,  4.7636e-02], device='cuda:0', │                           │
│ │          │      requires_grad=True)                                                    │                           │
│ │  input = tensor([[[[1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],             │                           │
│ │          │   │     [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],             │                           │
│ │          │   │     [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],             │                           │
│ │          │   │     ...,                                                                │                           │
│ │          │   │     [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],             │                           │
│ │          │   │     [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],             │                           │
│ │          │   │     [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000]],            │                           │
│ │          │   │                                                                         │                           │
│ │          │   │    [[0.0471, 0.0549, 0.0431,  ..., 0.0549, 0.0549, 0.0549],             │                           │
│ │          │   │     [0.0392, 0.0392, 0.0431,  ..., 0.0706, 0.0549, 0.0627],             │                           │
│ │          │   │     [0.0431, 0.0510, 0.0510,  ..., 0.0627, 0.0627, 0.0627],             │                           │
│ │          │   │     ...,                                                                │                           │
│ │          │   │     [0.0824, 0.0784, 0.0706,  ..., 0.0235, 0.0235, 0.0275],             │                           │
│ │          │   │     [0.0706, 0.0745, 0.0745,  ..., 0.0275, 0.0275, 0.0235],             │                           │
│ │          │   │     [0.0667, 0.0667, 0.0667,  ..., 0.0314, 0.0314, 0.0314]],            │                           │
│ │          │   │                                                                         │                           │
│ │          │   │    [[0.0902, 0.0902, 0.0863,  ..., 0.1020, 0.0980, 0.0980],             │                           │
│ │          │   │     [0.0980, 0.0980, 0.1020,  ..., 0.1137, 0.1098, 0.1137],             │                           │
│ │          │   │     [0.0863, 0.1020, 0.1020,  ..., 0.1059, 0.1059, 0.1059],             │                           │
│ │          │   │     ...,                                                                │                           │
│ │          │   │     [0.1137, 0.1098, 0.1098,  ..., 0.0745, 0.0706, 0.0784],             │                           │
│ │          │   │     [0.1098, 0.1216, 0.1137,  ..., 0.0784, 0.0745, 0.0745],             │                           │
│ │          │   │     [0.1098, 0.1098, 0.1098,  ..., 0.0784, 0.0784, 0.0824]],            │                           │
│ │          │   │                                                                         │                           │
│ │          │   │    [[0.0706, 0.0667, 0.0667,  ..., 0.0941, 0.0980, 0.1020],             │                           │
│ │          │   │     [0.0471, 0.0471, 0.0510,  ..., 0.1059, 0.0941, 0.1098],             │                           │
│ │          │   │     [0.0667, 0.0549, 0.0549,  ..., 0.1020, 0.1020, 0.1020],             │                           │
│ │          │   │     ...,                                                                │                           │
│ │          │   │     [0.0706, 0.0706, 0.0706,  ..., 0.0510, 0.0706, 0.0549],             │                           │
│ │          │   │     [0.0706, 0.0706, 0.0745,  ..., 0.0549, 0.0706, 0.0510],             │                           │
│ │          │   │     [0.0588, 0.0588, 0.0588,  ..., 0.0745, 0.0745, 0.0588]]]],          │                           │
│ │          │      device='cuda:0')                                                       │                           │
│ │   self = Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))              │                           │
│ │ weight = Parameter containing:                                                         │                           │
│ │          tensor([[[[ 6.2528e-02,  1.5936e-01, -1.5874e-01],                            │                           │
│ │          │   │     [-9.9415e-02, -5.9671e-02,  8.6597e-02],                            │                           │
│ │          │   │     [ 3.7585e-02,  1.8840e-01, -3.7357e-02]],                           │                           │
│ │          │   │                                                                         │                           │
│ │          │   │    [[ 8.3239e-02, -4.8833e-02, -2.3828e-02],                            │                           │
│ │          │   │     [-2.0116e-01, -2.1700e-01, -1.2862e-01],                            │                           │
│ │          │   │     [ 4.8813e-03,  2.0031e-02,  5.9585e-02]],                           │                           │
│ │          │   │                                                                         │                           │
│ │          │   │    [[-1.3911e-01, -8.6602e-02,  7.9386e-02],                            │                           │
│ │          │   │     [ 2.0256e-01, -5.8057e-02,  1.6181e-01],                            │                           │
│ │          │   │     [-3.5710e-02,  9.5354e-05,  1.0852e-01]]],                          │                           │
│ │          │   │                                                                         │                           │
│ │          │   │                                                                         │                           │
│ │          │   │   [[[-1.4971e-01, -6.6270e-02,  1.5299e-02],                            │                           │
│ │          │   │     [-4.2421e-02,  2.8225e-01, -6.9907e-02],                            │                           │
│ │          │   │     [-4.0138e-02, -1.0444e-01, -1.2691e-01]],                           │                           │
│ │          │   │                                                                         │                           │
│ │          │   │    [[-1.0122e-01,  2.1170e-01,  1.0550e-01],                            │                           │
│ │          │   │     [ 1.1277e-01,  5.3004e-02, -8.8985e-02],                            │                           │
│ │          │   │     [ 5.5754e-02, -2.0048e-01, -1.3112e-01]],                           │                           │
│ │          │   │                                                                         │                           │
│ │          │   │    [[-1.3039e-01,  1.1972e-01,  9.7248e-02],                            │                           │
│ │          │   │     [-9.9422e-02,  1.9427e-02,  1.3587e-01],                            │                           │
│ │          │   │     [ 1.9719e-01,  8.1715e-02,  3.2493e-02]]],                          │                           │
│ │          │   │                                                                         │                           │
│ │          │   │                                                                         │                           │
│ │          │   │   [[[ 7.9002e-02, -1.7141e-01,  4.0762e-02],                            │                           │
│ │          │   │     [-2.1003e-01, -1.8662e-01, -7.3658e-02],                            │                           │
│ │          │   │     [ 9.4726e-02,  1.8988e-01, -2.5005e-02]],                           │                           │
│ │          │   │                                                                         │                           │
│ │          │   │    [[-2.8966e-03,  6.4510e-02, -5.5103e-02],                            │                           │
│ │          │   │     [-5.8947e-03,  9.7560e-02,  2.2617e-01],                            │                           │
│ │          │   │     [ 1.5516e-01, -1.4872e-01,  7.5949e-03]],                           │                           │
│ │          │   │                                                                         │                           │
│ │          │   │    [[ 1.5783e-02,  1.6798e-01,  1.4967e-01],                            │                           │
│ │          │   │     [ 1.9338e-01,  5.3073e-02, -2.3900e-01],                            │                           │
│ │          │   │     [-7.6756e-02, -1.8026e-01, -1.8623e-01]]],                          │                           │
│ │          │   │                                                                         │                           │
│ │          │   │                                                                         │                           │
│ │          │   │   ...,                                                                  │                           │
│ │          │   │                                                                         │                           │
│ │          │   │                                                                         │                           │
│ │          │   │   [[[ 5.3663e-02, -3.4132e-02, -1.5040e-01],                            │                           │
│ │          │   │     [ 9.1144e-02,  8.9129e-02, -1.2544e-01],                            │                           │
│ │          │   │     [-1.4803e-01,  1.3906e-01,  1.7878e-01]],                           │                           │
│ │          │   │                                                                         │                           │
│ │          │   │    [[-3.2644e-02, -9.9829e-02,  8.7232e-02],                            │                           │
│ │          │   │     [-3.2350e-02, -2.4906e-01, -1.2619e-01],                            │                           │
│ │          │   │     [ 5.4103e-02,  1.2756e-01, -7.5880e-02]],                           │                           │
│ │          │   │                                                                         │                           │
│ │          │   │    [[ 4.2040e-02, -1.0263e-01,  1.8475e-01],                            │                           │
│ │          │   │     [ 7.6832e-02,  4.5077e-02,  1.2690e-01],                            │                           │
│ │          │   │     [ 2.4022e-02, -1.8540e-01, -6.2742e-02]]],                          │                           │
│ │          │   │                                                                         │                           │
│ │          │   │                                                                         │                           │
│ │          │   │   [[[ 1.1645e-01, -2.5826e-02,  2.3305e-01],                            │                           │
│ │          │   │     [-2.0772e-02, -2.1681e-01, -7.7740e-02],                            │                           │
│ │          │   │     [-1.5601e-01,  1.9904e-01, -6.5023e-02]],                           │                           │
│ │          │   │                                                                         │                           │
│ │          │   │    [[-1.6049e-01, -2.9661e-02, -1.9432e-01],                            │                           │
│ │          │   │     [-1.0756e-01,  1.6988e-01, -1.8802e-01],                            │                           │
│ │          │   │     [ 1.3381e-01,  1.8214e-01,  6.6247e-03]],                           │                           │
│ │          │   │                                                                         │                           │
│ │          │   │    [[ 8.0403e-02, -1.5402e-01,  1.2374e-01],                            │                           │
│ │          │   │     [ 2.2122e-01,  1.1959e-02,  1.7979e-01],                            │                           │
│ │          │   │     [-1.9051e-01, -8.9927e-02,  8.5409e-03]]],                          │                           │
│ │          │   │                                                                         │                           │
│ │          │   │                                                                         │                           │
│ │          │   │   [[[-1.5390e-01,  9.4147e-02, -6.6585e-02],                            │                           │
│ │          │   │     [-8.9182e-02, -1.9101e-01,  9.6017e-02],                            │                           │
│ │          │   │     [-1.6498e-01, -7.0757e-02,  8.8481e-02]],                           │                           │
│ │          │   │                                                                         │                           │
│ │          │   │    [[ 1.8690e-01,  5.7642e-02, -6.4977e-02],                            │                           │
│ │          │   │     [-6.7021e-02,  1.3403e-01,  5.2437e-02],                            │                           │
│ │          │   │     [ 1.7144e-01,  7.5775e-02,  1.5011e-01]],                           │                           │
│ │          │   │                                                                         │                           │
│ │          │   │    [[-1.5898e-01,  1.3963e-01, -1.1352e-01],                            │                           │
│ │          │   │     [-6.3690e-02, -2.0617e-02, -7.5160e-02],                            │                           │
│ │          │   │     [ 2.1231e-02,  1.5457e-01, -1.7909e-01]]]], device='cuda:0',        │                           │
│ │          │      requires_grad=True)                                                    │                           │
│ ╰────────────────────────────────────────────────────────────────────────────────────────╯                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Given groups=1, weight of size [64, 3, 3, 3], expected input[1, 4, 192, 192] to have 3 channels, but got 4
channels instead
