### ISSUE TITLE
Cv2 error

### ISSUE THREAD

**Issue by caninereason** [TingTingin/TikTokDiffusion#3]
Hey Ting, great wortk, although I seem to have a problem with cv2, Ive reinstalled numpy etc...

Checking TikTokDiffusion Requirement: yt_dlp
Traceback (most recent call last):
  File "D:\ml-agent\stable-diffusion-webui\TikTokDiffusion\TikTokDiffusion.py", line 73, in <module>
    import track
  File "D:\ml-agent\stable-diffusion-webui\TikTokDiffusion\track.py", line 54, in <module>
    from yolov5.models.common import DetectMultiBackend
  File "D:\ml-agent\stable-diffusion-webui\TikTokDiffusion\yolov5\models\common.py", line 27, in <module>
    from utils.dataloaders import exif_transpose, letterbox
  File "D:\ml-agent\stable-diffusion-webui\TikTokDiffusion\yolov5\utils\dataloaders.py", line 31, in <module>
    from utils.augmentations import (Albumentations, augment_hsv, classify_albumentations, classify_transforms, copy_paste,
  File "D:\ml-agent\stable-diffusion-webui\TikTokDiffusion\yolov5\utils\augmentations.py", line 15, in <module>
    from utils.general import LOGGER, check_version, colorstr, resample_segments, segment2box, xywhn2xyxy
  File "D:\ml-agent\stable-diffusion-webui\TikTokDiffusion\yolov5\utils\general.py", line 55, in <module>
    cv2.setNumThreads(0)  # prevent OpenCV from multithreading (incompatible with PyTorch DataLoader)
AttributeError: module 'cv2' has no attribute 'setNumThreads'
Press any key to continue . . .

(venv) D:\ml-agent\stable-diffusion-webui>python TikTokDiffusion\TikTokDiffusion.py
Checking TikTokDiffusion...
Checking TikTokDiffusion Requirement: gitpython
Checking TikTokDiffusion Requirement: ipython
Checking TikTokDiffusion Requirement: matplotlib
Checking TikTokDiffusion Requirement: numpy
Checking TikTokDiffusion Requirement: cv2
Checking TikTokDiffusion Requirement: orjson
Checking TikTokDiffusion Requirement: PIL
Checking TikTokDiffusion Requirement: psutil
Checking TikTokDiffusion Requirement: yaml
Checking TikTokDiffusion Requirement: requests
Checking TikTokDiffusion Requirement: scipy
Checking TikTokDiffusion Requirement: thop
Checking TikTokDiffusion Requirement: SSIM_PIL
Checking TikTokDiffusion Requirement: moviepy
Checking TikTokDiffusion Requirement: sklearn
Checking TikTokDiffusion Requirement: dface
Checking TikTokDiffusion Requirement: tqdm
Checking TikTokDiffusion Requirement: flet
Checking TikTokDiffusion Requirement: static_ffmpeg
Checking TikTokDiffusion Requirement: ffmpeg
Checking TikTokDiffusion Requirement: tensorboard
Checking TikTokDiffusion Requirement: pandas
Checking TikTokDiffusion Requirement: seaborn
Checking TikTokDiffusion Requirement: easydict
Checking TikTokDiffusion Requirement: gdown
Checking TikTokDiffusion Requirement: lap
Checking TikTokDiffusion Requirement: cython_bbox
Checking TikTokDiffusion Requirement: filterpy
Checking TikTokDiffusion Requirement: pyopencl
Checking TikTokDiffusion Requirement: yt_dlp
Traceback (most recent call last):
  File "D:\ml-agent\stable-diffusion-webui\TikTokDiffusion\TikTokDiffusion.py", line 73, in <module>
    import track
  File "D:\ml-agent\stable-diffusion-webui\TikTokDiffusion\track.py", line 54, in <module>
    from yolov5.models.common import DetectMultiBackend
  File "D:\ml-agent\stable-diffusion-webui\TikTokDiffusion\yolov5\models\common.py", line 27, in <module>
    from utils.dataloaders import exif_transpose, letterbox
  File "D:\ml-agent\stable-diffusion-webui\TikTokDiffusion\yolov5\utils\dataloaders.py", line 31, in <module>
    from utils.augmentations import (Albumentations, augment_hsv, classify_albumentations, classify_transforms, copy_paste,
  File "D:\ml-agent\stable-diffusion-webui\TikTokDiffusion\yolov5\utils\augmentations.py", line 15, in <module>
    from utils.general import LOGGER, check_version, colorstr, resample_segments, segment2box, xywhn2xyxy
  File "D:\ml-agent\stable-diffusion-webui\TikTokDiffusion\yolov5\utils\general.py", line 55, in <module>
    cv2.setNumThreads(0)  # prevent OpenCV from multithreading (incompatible with PyTorch DataLoader)
AttributeError: module 'cv2' has no attribute 'setNumThreads'

**Comment by TingTingin** [comment]
did you solve this?

**Comment by caninereason** [comment]
closed as 'pip install opencv-python==4.5.5.64' seemed to fix it, idk I had low disk space when running dependencies and I think it screwed some stuff up
