### ISSUE TITLE
I got a type error with TrackFaces DetectBodies

### ISSUE THREAD

**Issue by barleyj21** [TingTingin/TikTokDiffusion#6]
Running on win10
with Nightly version of pyTorch
But I think it's not related to issue

```
Finished Face Search For 16/16 Images
This Batch Took 3.698764899978414 seconds
Loading face checking models (FaceNet).
Downloading: "https://github.com/deepware/dFace/raw/master/models/facenet.pt" to C:\Users\user1/.cache\torch\hub\checkpoints\facenet.pt
100%|██████████████████████████████████████████████████████████████████████████████| 89.8M/89.8M [02:37<00:00, 598kB/s]
Grouping faces by identity current sensitvity: is 0.1
Exception in thread Thread-336 (this_func):
Traceback (most recent call last):
  File "C:\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "R:\a1111\webui\TikTokDiffusion\TikTokDiffusion.py", line 1024, in this_func
    status = track.test_main(image_folder=image_folder, skip_if_exists=skip_if_exists, steps=steps,
  File "R:\a1111\webui\TikTokDiffusion\track.py", line 977, in test_main
    run(source=Path(image_folder), **vars(opt),
  File "R:\a1111\webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "R:\a1111\webui\TikTokDiffusion\track.py", line 660, in run
    person_list.get_prompts() #assigns prompts to people and groups images by the path to the file
  File "R:\a1111\webui\TikTokDiffusion\track.py", line 363, in get_prompts
    get_missing()
  File "R:\a1111\webui\TikTokDiffusion\track.py", line 347, in get_missing
    if person.track_label > len(func_prompt_list):
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

**Comment by TingTingin** [comment]
Check faces doesn't work properly in the current version

**Comment by TingTingin** [comment]
Check faces is for if you want to match people in different scenes with the same prompt and face since track bodies only works if the camera angle doesn't change or it the person doesn't leave the frame

**Comment by barleyj21** [comment]
I found you video here about it, after I posted this. Still everything else seems to be working, but my embeddings just don't cut it, even on 8 loops for 1 image. Will have to train LORAs

**Comment by TingTingin** [comment]
You can try increasing the Denoising if it doesn't look like the character and increase the resolution

**Comment by barleyj21** [comment]
Well I still can't really pin the balance. With higher denoising (about 0.5) I get face that doesn't move facial features and doesn't care for underlying image. I either need to try more to adapt to my embeddings or train lora and try from there
