### ISSUE TITLE
issue with running after selecting video

### ISSUE THREAD

**Issue by Vincevinny** [TingTingin/TikTokDiffusion#7]
it splits the frames and creates the masks then i get this error

i have had soo many issues getting this installed fixed 3 of them myself but i cant work this one out please help me green ting i really want to use this program it looks **amazing.**

i tried manually downloading the LDSR ckpt and putting it in the LDSR folder in automatic still the same error 

tiktok diffusion cmd error

generating prompt: 'emma watson' for person 1
Exception in thread Thread-61 (this_func):
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "E:\stable-diffusion-webui\TikTokDiffusion\TikTokDiffusion.py", line 1024, in this_func
    status = track.test_main(image_folder=image_folder, skip_if_exists=skip_if_exists, steps=steps,
  File "E:\stable-diffusion-webui\TikTokDiffusion\track.py", line 977, in test_main
    run(source=Path(image_folder), **vars(opt),
  File "C:\Users\Vince\AppData\Roaming\Python\Python310\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\stable-diffusion-webui\TikTokDiffusion\track.py", line 898, in run
    image = api.img2img(images=[gen_image],
  File "E:\stable-diffusion-webui\TikTokDiffusion\webuiapi.py", line 216, in img2img
    return self._to_api_result(response)
  File "E:\stable-diffusion-webui\TikTokDiffusion\webuiapi.py", line 47, in _to_api_result
    raise RuntimeError(response.status_code, response.text)
RuntimeError: (500, 'Internal Server Error')

and the automatic1111 cmd error
Downloading: "https://heibox.uni-heidelberg.de/f/578df07c8fc04ffbadf3/?dl=1" to E:\stable-diffusion-webui\models\LDSR\model.ckpt

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "E:\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 94, in receive
    return self.receive_nowait()
  File "E:\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 89, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 77, in call_next
    message = await recv_stream.receive()
  File "E:\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 114, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\stable-diffusion-webui\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "E:\stable-diffusion-webui\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "E:\stable-diffusion-webui\venv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "E:\stable-diffusion-webui\venv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "E:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "E:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "E:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 106, in __call__
    response = await self.dispatch_func(request, call_next)
  File "E:\stable-diffusion-webui\modules\api\api.py", line 96, in log_and_time
    res: Response = await call_next(req)
  File "E:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 80, in call_next
    raise app_exc
  File "E:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 69, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "E:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "E:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 43, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "E:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "E:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "E:\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "E:\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "E:\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "E:\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "E:\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "E:\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "E:\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "E:\stable-diffusion-webui\venv\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "E:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\stable-diffusion-webui\modules\api\api.py", line 246, in img2imgapi
    processed = process_images(p)
  File "E:\stable-diffusion-webui\modules\processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "E:\stable-diffusion-webui\modules\processing.py", line 577, in process_images_inner
    p.init(p.all_prompts, p.all_seeds, p.all_subseeds)
  File "E:\stable-diffusion-webui\modules\processing.py", line 985, in init
    image = images.resize_image(2, image, self.width, self.height)
  File "E:\stable-diffusion-webui\modules\images.py", line 295, in resize_image
    resized = resize(im, src_w, src_h)
  File "E:\stable-diffusion-webui\modules\images.py", line 267, in resize
    im = upscaler.scaler.upscale(im, scale, upscaler.data_path)
  File "E:\stable-diffusion-webui\modules\upscaler.py", line 63, in upscale
    img = self.do_upscale(img, selected_model)
  File "E:\stable-diffusion-webui\extensions-builtin\LDSR\scripts\ldsr_model.py", line 54, in do_upscale
    ldsr = self.load_model(path)
  File "E:\stable-diffusion-webui\extensions-builtin\LDSR\scripts\ldsr_model.py", line 40, in load_model
    model = load_file_from_url(url=self.model_url, model_dir=self.model_path,
  File "E:\stable-diffusion-webui\venv\lib\site-packages\basicsr\utils\download_util.py", line 98, in load_file_from_url    download_url_to_file(url, cached_file, hash_prefix=None, progress=progress)
  File "E:\stable-diffusion-webui\venv\lib\site-packages\torch\hub.py", line 597, in download_url_to_file
    u = urlopen(req)
  File "C:\Program Files\Python310\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files\Python310\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "C:\Program Files\Python310\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Program Files\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Program Files\Python310\lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Program Files\Python310\lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)>

**Comment by Vincevinny** [comment]
well i was keen to make it work so i read the other issues and this one fixed it for me
https://github.com/TingTingin/TikTokDiffusion/issues/4#issue-1590669386
